// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/process": {
            "post": {
                "description": "Trigger worker pool to process all CSV files",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processor"
                ],
                "summary": "Start concurrent CSV processing",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.Result"
                            }
                        }
                    }
                }
            }
        },
        "/progress": {
            "get": {
                "description": "Returns how many records have been processed so far",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Processor"
                ],
                "summary": "Get processing progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.Result": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "file": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "rows": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Concurrent Data Processing API",
	Description:      "Concurrent CSV processor with worker pool and REST interface",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
