CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(150),
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    email_verified BOOLEAN DEFAULT false,
    bio TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deactivated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    ip_address VARCHAR(45),
    user_agent TEXT,
    role VARCHAR(50),
    gender VARCHAR(20),
    country_code VARCHAR(10),
    phone_number VARCHAR(30),
    location TEXT,
    nationality VARCHAR(100),
    national_id_number VARCHAR(100),
    language VARCHAR(10),
    birthdate DATE
);
