CREATE TABLE IF NOT EXISTS posts (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL DEFAULT 'article',
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    excerpt TEXT,
    seo_title VARCHAR(255),
    seo_excerpt TEXT,
    content JSONB,
    content_html TEXT,
    content_text TEXT,
    tags TEXT[],
    thumbnail TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    is_featured BOOLEAN DEFAULT false,
    is_pinned BOOLEAN DEFAULT false,
    visibility VARCHAR(50) NOT NULL DEFAULT 'public',
    metadata JSONB,
    total_views INT DEFAULT 0,
    language VARCHAR(10),
    read_time INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    scheduled_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
